name: 孙炳义
bio: '测试'

# main text of home
picture: 'assets/images/profile.jpg'

url: http://sunbingyi.github.io
# your url: http://USERNAME.github.io
# if testing locally: http://localhost:3000

permalink: /:title/

markdown: kramdown
highlighter: rouge

analytics-google: 'UA-MYANALYTICS'
disqus: mydisqus

# if you don't have any of social below, set to false then
# facebook: myfacebook
# twitter: mytwitter
# instagram: myinstagram
# linkedin: mylinkedin
# youtube: myyoutube
# spotify: myspotify
# github: sunyuhui
email: 358645302@qq.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor]

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: true

# if you don't need about or blog, comment them out below
about: true
blog: true

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com
